version: '3'

services:
    web:
        build: ./src
        volumes:
            - ./src:/code
        # ports:
        #     - "80:5000"
        # links:
        #     - redis:redis
        command: python main.py
    # redis:
    #     image: redis:5.0.4
    #     ports:
    #         - "6379:6379"
    #     volumes:
    #         - db-data:/data

# volumes:
#     db-data:
